# 指定运行端口
server:
  port: 8011

# 指定服务名称
spring:
  application:
    name: eureka-client

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://root:root@eureka8001:8001/eureka/,http://root:root@eureka8002:8002/eureka,http://root:root@eureka8003:8003/eureka
