server:
  port: 2002

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://c.biancheng.net
          predicates:
            - Path=/spring_cloud

# actuator配置
management:
  server:
    port: 12002
#    servlet:
#      context-path: /
#    ssl:
#      enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true # 启用shutdown端点优雅关机 POST http://localhost:10212/actuator/shutdown
