# 指定运行端口
server:
  port: 8002

# 指定服务名称
spring:
  application:
    name: eureka-server

# 指定主机地址
eureka:
  instance:
    hostname: eureka8002
    metadata-map:
      zone: hangzhou #所在区域
    #是否优先使用ip来作为主机名
    prefer-ip-address: true
  client:
    # 指定是否从注册中心获取服务(注册中心不需要开启)
    fetch-registry: false
    # 指定是否将服务注册到注册中心(注册中心不需要开启)
    register-with-eureka: false
    serviceUrl:
      # 注册到另一个Eureka注册中心
      defaultZone: http://${eureka-server.eureka8001.host}:${eureka-server.eureka8001.port}/eureka,http://${eureka-server.eureka8003.host}:${eureka-server.eureka8003.port}/eureka